Dev
ArtCode-Kazan/SeismicFileConverter pull request #1
Opened 2022-12-29 07:49 UTC by fotuka

2023-01-10 13:58 UTC, MikkoArtik requested changes
Жду правки в UI-модуле

2023-01-10 13:58 UTC, MikkoArtik commented on MainConverterWindow.cs
> +            toolStripStatusLabel1.Text = "Ready";
нужно сделать актуальное именование UI-элементов. Здесь можно просто указать - StatusLabel

2023-01-10 13:58 UTC, MikkoArtik commented on MainConverterWindow.cs
> +        public void buttonBrowse_Click(object sender, EventArgs e)
имя метода нужно поменять - неясно его назанчение из названия

2023-01-10 13:58 UTC, MikkoArtik commented on MainConverterWindow.cs
> +            if (openFileDialog1.ShowDialog() == DialogResult.OK)
openFileDialog1 - измени дефолное имя на корректное

2023-01-10 13:58 UTC, MikkoArtik commented on MainConverterWindow.cs
> +                    pathsToJsonFiles.Add(file);
можно добавить this. пока что

2023-01-10 13:58 UTC, MikkoArtik commented on MainConverterWindow.cs
> +        internal void buttonSaveBrowse_Click(object sender, EventArgs e)
имя метода необходимо сделать более корректным

2023-01-10 13:58 UTC, MikkoArtik commented on MainConverterWindow.cs
> +                pathToSaveBinaryFileFolder = folderBrowserDialog1.SelectedPath;
добавить this

2023-01-10 13:58 UTC, MikkoArtik commented on MainConverterWindow.cs
> +        internal void buttonGo_Click(object sender, EventArgs e)
Здесь можно назвать UI эл-т как buttonConvert

2023-01-10 13:58 UTC, MikkoArtik commented on MainConverterWindow.cs
> +            foreach (string path in pathsToJsonFiles)
добавить this

2023-01-10 13:58 UTC, MikkoArtik commented on MainConverterWindow.cs
> +                JsonToBinary jsonya = new JsonToBinary(path, pathToSaveBinaryFileFolder);
некорректное имя переменной

2023-01-10 13:58 UTC, MikkoArtik commented on MainConverterWindow.cs
> +                JsonToBinary jsonya = new JsonToBinary(path, pathToSaveBinaryFileFolder);
JsonToBinary больше похоже на название метода, а не класса

2023-01-10 13:58 UTC, MikkoArtik commented on MainConverterWindow.cs
> +                statusStrip1.Refresh();
Старайся не использовать дефолтные имена компонентов

2023-01-10 13:58 UTC, MikkoArtik commented on MainConverterWindow.cs
> +            Help.ShowHelp(this, exeDirectory + "\\" + "JsonСonverter.chm");
Имя справки JsonСonverter.chm вынеси в константы. Не используй константы внутри кода

2023-01-10 13:58 UTC, MikkoArtik commented on MainConverterWindow.cs
> +            Help.ShowHelp(this, exeDirectory + "\\" + "JsonСonverter.chm");
Сделать проверку наличия файла справки. Учесть, что справки может и не быть

2023-01-11 09:46 UTC, fotuka commented
https://github.com/ArtCode-Kazan/SeismicFileConverter/pull/1#discussion_r1065800400

2023-01-11 13:35 UTC, MikkoArtik requested changes
Жду правок основного модуля - JsonBinLib

2023-01-11 13:35 UTC, MikkoArtik commented on JsonBinLib/JsonBinLib.cs
>          public Int32[] NormalizeNConvertSignal(float[] originSignal)
Перегруппируй методы. Те, которые не используют другие методв класса, должны идти выше, чем те методы, которые их используют

2023-01-11 13:35 UTC, MikkoArtik commented on JsonBinLib/JsonBinLib.cs
>              return signalInInt32;
Опечатка - coeffNorm

2023-01-11 13:35 UTC, MikkoArtik commented on JsonBinLib/JsonBinLib.cs
>                      int columnIndex = 1 * sizeof(int);
что за единица?

2023-01-11 13:35 UTC, MikkoArtik commented on JsonBinLib/JsonBinLib.cs
> +        public void ConvertAndSave()
пробелы между методами потеряны

2023-01-11 18:16 UTC, MikkoArtik requested changes
Требуемый подход не реалиован

2023-01-11 18:16 UTC, MikkoArtik commented on JsonBinLib/JsonBinLib.cs
>          public DateTime start_time { get; set; }
Давай еще в этот класс-контейнер добавим поля:
- frequency
- componentName (X, Y or Z)

2023-01-11 18:16 UTC, MikkoArtik commented on JsonBinLib/JsonBinLib.cs
>      public class JsonClass
переименовать в JsonDataContainer

2023-01-12 06:28 UTC, MikkoArtik requested changes
По структуре программы все верно. Замечания к коду добавлены.
Необходимо дополнить файл gitignore для того, чтобы в репозиторий не попали cache-файлы и прочий мусор

2023-01-12 06:28 UTC, MikkoArtik commented on JsonBinLib/JsonBinLib.cs
> +    public class JsonDataContainer
Этот класс должен идти первым в модуле, так дальше он используется другими классами (аналогия с сортировкой методов внутри класса)

2023-01-12 06:28 UTC, MikkoArtik commented on JsonBinLib/JsonBinLib.cs
> +        public int componentName { get; set; }
изменить тип на string

2023-01-12 06:28 UTC, MikkoArtik commented on JsonBinLib/JsonBinLib.cs
> +    public class SeisJsonParser
Этот класс должен идти вторым

2023-01-12 06:28 UTC, MikkoArtik commented on JsonBinLib/JsonBinLib.cs
> +    public class SeisJsonParser
можно назвать просто - JsonParser

2023-01-12 06:28 UTC, MikkoArtik commented on JsonBinLib/JsonBinLib.cs
>          private int componentOffset = 1;
Константы лучше вынести в отдельный класс (как в SeisReader dll)

2023-01-12 06:28 UTC, MikkoArtik commented on JsonBinLib/JsonBinLib.cs
>          }
Проверить алгоритм нормализации, реализован неверно

2023-01-12 06:28 UTC, MikkoArtik commented on MainConverterWindow.cs
>          public string helpFileName = "JsonСonverter.chm";
тип - константа

2023-01-12 06:28 UTC, MikkoArtik commented on MainConverterWindow.cs
>              }
Использовать path combine

2023-01-12 10:41 UTC, MikkoArtik requested changes
Не убран JsonBinLib/obj/Debug/JsonBinLib.csproj.AssemblyReference.cache.
Жду правок по коду

2023-01-12 12:19 UTC, MikkoArtik requested changes
Жду правки

2023-01-12 12:19 UTC, MikkoArtik commented on JsonBinLib/JsonBinLib.cs
> +            double amplitudeCorrectCoeff = Constants.NormalizationMaximum + (minimumOrigin * coeffNorm);
переименуй со словом offset

2023-01-12 13:30 UTC, MikkoArtik requested changes
Необходиом поработать над методом записи в файл

2023-01-12 13:30 UTC, MikkoArtik commented on JsonBinLib/JsonBinLib.cs
> +                    Int32[] signalStack = new Int32[normalSignal.Length * 3];
тройка - это константа. заменить на Constants.channelsCount

2023-01-12 13:30 UTC, MikkoArtik commented on JsonBinLib/JsonBinLib.cs
> +                        binaryWriter.Write(BitConverter.GetBytes(signalStack[i]));
Убрать зависимость от цифры 3

2023-01-12 13:47 UTC, MikkoArtik requested changes
Ревью практически сдано

2023-01-12 13:47 UTC, MikkoArtik commented on JsonBinLib/JsonBinLib.cs
> +                                binaryWriter.Write(BitConverter.GetBytes(Constants.nullValue));
не до конца исправлено нарушение принципа DRY

2023-01-12 13:52 UTC, MikkoArtik approved these changes
Ревью прошло успешно. Можно мержить

2023-01-12 13:52 UTC, merged