Dev updater
ArtCode-Kazan/SeismicFileConverter pull request #5
Opened 2023-01-18 13:58 UTC by fotuka

2023-01-19 13:25 UTC, MikkoArtik requested changes
Жду правки

2023-01-19 14:47 UTC, MikkoArtik requested changes
Жду правок.
Особо обратить внимание на две вещи:
- выделение отдельной сущности парсера файла с описанием версии программы
- именование переменных. Надо просмотреть весь написанный код (dll тоже), нужно поправить

2023-01-19 14:47 UTC, MikkoArtik commented on MainConverterWindow.cs
> +            string s;
назвать line

2023-01-19 14:47 UTC, MikkoArtik commented on MainConverterWindow.cs
> +            ProcessStartInfo info = new ProcessStartInfo(Path.Combine(ProgrammFolderPath, "SeisJsonConverterUpdater.exe"));
вынести в константу

2023-01-19 14:47 UTC, MikkoArtik commented on MainConverterWindow.cs
> +            "Обновление",
почему на русском?

2023-01-19 14:47 UTC, MikkoArtik commented on MainConverterWindow.cs
> +                MessageBox.Show("Установлена последняя версия", "Обновление");
на русском

2023-01-19 14:47 UTC, MikkoArtik commented on Updater/FormUpdater.cs
> +        public List<string> MainFilesName = new List<string>()
Отлично подойдет FrienflyFileNames

2023-01-19 14:47 UTC, MikkoArtik commented on Updater/FormUpdater.cs
> +            string s;
использовать однобуквенные переменные (кроме индексов) - дурной тон

2023-01-19 14:47 UTC, MikkoArtik commented on MainConverterWindow.cs
> +        }
методы, относящиеся к одной сущности, нужно собрать в одном классе

2023-01-19 14:47 UTC, MikkoArtik commented on MainConverterWindow.cs
> +        }
тоже поместить в отдельную сущность

2023-01-19 14:47 UTC, MikkoArtik commented on Updater/FormUpdater.cs
> +            "SeisJsonConveterUpdater.pdb"
тоже вынести в константу

2023-01-19 14:47 UTC, MikkoArtik commented on Updater/FormUpdater.cs
> +            return result;
собрать в единую сущность парсинга файла description

2023-01-19 14:47 UTC, MikkoArtik commented on Updater/FormUpdater.cs
> +        }
тоже собрать в единую сущность

2023-01-19 14:47 UTC, MikkoArtik commented on Updater/FormUpdater.cs
> +            MessageBox.Show("Файл архива поврежден. Повторите попытку","Ошибка загрузки");
на русском. исправить на английский

2023-01-19 14:47 UTC, MikkoArtik commented on Updater/FormUpdater.cs
> +                if (!MainFilesName.Contains(Path.GetFileName(path)))
аргументы во всех методах сделать именованными:
пример
`PrintOrderDetails(productName: "Red Mug", sellerName: "Gift Shop", orderNum: 31);`

2023-01-19 14:47 UTC, MikkoArtik commented on Updater/FormUpdater.cs
> +            if (IsZipBroken() == false)
почему не написать:
`if (!IsZipBroken())`

2023-01-20 11:40 UTC, MikkoArtik requested changes
Нужно выделить работу с сервером, гдже хранится одновление, в отдельную dll.
Код исправить в соответствии с этой dll

2023-01-20 11:40 UTC, MikkoArtik commented on MainConverterWindow.cs
> +    }
логика сравнения версий не реализована

2023-01-20 11:40 UTC, MikkoArtik commented on MainConverterWindow.cs
> +        }
давай вынесем в отдельную dll реализацию. сюда же добавить вычисление hash-суммы

2023-01-20 11:40 UTC, MikkoArtik commented on Updater/FormUpdater.cs
>                      .ToLower();
может в одну строчку?

2023-01-20 14:09 UTC, MikkoArtik requested changes
Исправить нарушение принципа DRY, доработать правки по форматированию кода.
Обратить внимание на значения по умолчанию - некторые нужно сделать обязательными без значения по умолчанию.
Жду правки. Желательно PR #5 закрыть до 23/01/2023

2023-01-20 14:09 UTC, MikkoArtik commented on Updater/FormUpdater.cs
> +                if (this.serverInfo.IsHashsumEqual(GetZipHashSum(Path.Combine(programmFolderPath, Constants.ZipName))))
Разделить строку на несколько переменных

2023-01-20 14:09 UTC, MikkoArtik commented on Updater/FormUpdater.cs
> +            UpdaterLibPbd
Написать обращение к переменныим через Constants.

2023-01-21 18:37 UTC, MikkoArtik requested changes
Код плохого качества: содержит мусор, логические ошибки. Но форматирование кода стало лучше.
Скорее всего, следующий PR будет рассмотрен только при наличии Unit-тестов

2023-01-21 18:37 UTC, MikkoArtik commented on ServerConnector/ServerConnector.cs
> +    }
это не забыл, отлично

2023-01-21 18:37 UTC, MikkoArtik commented on ServerConnector/ServerConnector.cs
> +            }
нет обработки ошибок соединения. кажется, говорил, что нужно добавить

2023-01-21 18:37 UTC, MikkoArtik commented on ServerConnector/ServerConnector.cs
> +            if (GetDescription().version.Length == currentVersion.Length)
условие проверки неверное. подумай почему

2023-01-21 18:37 UTC, MikkoArtik commented on ServerConnector/ServerConnector.cs
> +            if (originHashsum == GetDescription().version)
условие неверное

2023-01-21 18:37 UTC, MikkoArtik commented on ServerConnector/ServerConnector.cs
> +        }
а если нет интернета?

2023-01-21 18:37 UTC, MikkoArtik commented on UpdaterLib/UpdaterLib.cs
>          }
метод задвоен

2023-01-21 18:38 UTC, fotuka commented on ServerConnector/ServerConnector.cs
> +            if (GetDescription().version.Length == currentVersion.Length)
тьфу, только щас понял

2023-01-27 12:53 UTC, MikkoArtik requested changes
Выполни небольшие правки и можно мержить

2023-01-27 12:53 UTC, MikkoArtik commented on MainConverterWindow.cs
> +                MessageBox.Show(text: exc.Message, caption: "Exception Caught!");
Заменить текст ошибки: No server connection

2023-01-27 12:53 UTC, MikkoArtik commented on Updater/FormUpdater.cs
> +                MessageBox.Show(text: exc.Message, caption: "Exception Caught!");
исправить текст ошибки на свой

2023-01-27 12:53 UTC, MikkoArtik commented on Updater/FormUpdater.cs
> +                    MessageBox.Show(text: exc.Message, caption: "Exception Caught!");
исправить текст ошибки на свой

2023-01-27 12:53 UTC, MikkoArtik commented on Updater/FormUpdater.cs
> +                    }
блок try-expect помести куда следует

2023-01-27 12:53 UTC, MikkoArtik commented on Updater/FormUpdater.cs
> +                MessageBox.Show(text: exc.Message, caption: "Exception Caught!");
исправить текст ошибки на свой

2023-01-27 14:24 UTC, merged